alias u="sudo pacman -Syu"
alias wttr="curl wttr.in"
alias myip="curl ipinfo.io/ip"
alias untar="tar -zxvf"
alias s="shasum -a 256"
alias y="yt-dlp -f bestvideo[ext=mp4]+bestaudio[ext=m4a] -i"
alias ya="yt-dlp -x --audio-format flac -i"
alias lt="ls -t -1 -S --color=auto --human-readable --size --classify"
alias lo="ls -1"
alias n="neofetch"
alias g="git"
alias nc="clear; neofetch"
alias sn="shutdown -P now"
alias rb="shutdown -r now"
alias k="killall -s SIGKILL"
alias c="clear"
alias cp="cp -iv"
alias m="mv -iv"
alias r="rm -v"
alias md="mkdir -pv"
alias ejectusb="udisksctl power-off -b"
alias quakespasm="quakespasm -basedir /home/noise/.quakespasm/"
alias ffmpeg="ffmpeg -hide_banner"
alias cdwine="cd /home/noise/.wine/drive_c; thunar"
alias vegas="prime-run wine64 ~/.wine/drive_c/Program\ Files/Sony/Vegas\ Pro\ 13.0/vegas130.exe"
neofetch
